name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest  # or use 'windows-latest' if needed

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # specify the desired Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # upgrade pip to the latest version
          python -m pip install virtualenv  # install virtualenv for creating isolated environments
          python -m venv venv  # create the virtual environment
          source venv/bin/activate  # activate the virtual environment
          pip install -r requirements.txt  # install dependencies from requirements.txt

      # Run tests with pytest, pylint, and coverage
      - name: Run Tests
        run: |
          source venv/bin/activate  # activate the virtual environment
          pytest --pylint --cov  # run tests, linting, and coverage checking
